# Site settings
title: MaPan - Blog
url: http://mapan1984.github.io
email: mapan1984@outlook.com
github_username: mapan1984

description: > # this means to ignore newlines until "baseurl:"
  My personal blog.
baseurl: "" # the subpath of your site, e.g. /blog


sass:
    sass_dir: _sass
    style: compress

# Build settings
#
## markdown
markdown: kramdown
highlighter: rouge
#
## paginator
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
#
permalink: pretty

# server
port: 5000
host: 127.0.0.1

# defaults
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
