# Site settings
title: MaPan - Blog
email: mapan1984@outlook.com 
github_username: mapan1984

description: > # this means to ignore newlines until "baseurl:"
  The best time to plant a tree was 10 years ago, The second best time is now.
baseurl: "" # the subpath of your site, e.g. /blog

# pages
paginate: 5
paginate_path: "page:num"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge 

sass:
    style: compressed
