# Site
title: MaPan - Blog
url: https://mapan1984.github.io
email: mapan1984@outlook.com
github_username: mapan1984
description: MaPan's personal blog.

# Build
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

# Pagination
plugins: [jekyll-paginate]
paginate: 15
paginate_path: "/page:num/"

# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: "_posts/algorithm"
    values:
      categories: ["Algorithm"]
  - scope:
      path: "_posts/manual"
    values:
      categories: ["Manual"]
  - scope:
      path: "_posts/network"
    values:
      categories: ["Network"]
  - scope:
      path: "_posts/note"
    values:
      categories: ["Note"]
  - scope:
      path: "_posts/program"
    values:
      categories: ["Program"]
  - scope:
      path: "_posts/system"
    values:
      categories: ["System"]
  - scope:
      path: "_posts/service"
    values:
      categories: ["Service"]
  - scope:
      path: "_posts/tool"
    values:
      categories: ["Tool"]
